name: Train Xception

on:
  push:
  pull_request: 
    types: [opened]

jobs:
  
  train-xception:
    runs-on: ubuntu-latest
    container: 
      image: nclgbd/mltraindev:develop
      # credentials:
      #   username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #   password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - uses: iterative/setup-dvc@v1
    - name: Setup env
      run: |
        dvc get https://github.com/iterative/dataset-registry tutorials/versioning/data.zip
        unzip data.zip
        mv data/train .
        mv data/validation .

        # Remove the directories since they're not needed anymore
        rm -f data.zip
        rm -rf data/train
        rm -rf data/validation
    - name: Train model
    - name: Run test scripts
      shell: bash -l {0}
      run: |
        mkdir -p media/ incorrect_images/ saved_models/
        ls -a
        conda activate torch_base
        python -m pytorch_vision_utils.train --model_name "xception" --parameters_path "parameters.json" --debug "False"
        zip -r media_xception.zip media
    
    - name: Save xception model
      uses: actions/upload-artifact@v2
      with:
        name: xception
        path: saved_models/xception.pth
    - name: Save xception report
      uses: actions/upload-artifact@v2
      with:
        name: xception_report
        path: media_xception.zip
